name: build

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - cygwin
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'

      - name: install cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: |
            binutils, gcc-core, gcc-g++, libpcre2-devel,
            ninja, git, perl, cmake, zlib-devel, libiconv-devel

      - name: cmake build
        env:
          SHELLOPTS: igncr
          CHERE_INVOKING: 1
        shell: bash
        run: |
            cmake -B build -DCMAKE_BUILD_TYPE=Release &&cmake --build build --config Release

